#!/usr/bin/expect -f
#

source $srcdir/mdb.exp

set file $srcdir/module.c
set foo $srcdir/foo.c

mdb_start "module" [pwd]/libfoo.so
mdb_expect_frame 0 "main" $file 11
mdb_send "library [pwd]/libfoo.so"
mdb_expect "Loaded library [pwd]/libfoo.so."
# FIXME: Wait until the debugger reloaded the symtabs
sleep 5
mdb_send "break hello"
mdb_expect_breakpoint
mdb_send "continue"
mdb_expect_stopped 0 "hello" $foo 9
