#!/usr/bin/expect -f
#

source $srcdir/mdb.exp

set file $srcdir/MultiThread.cs
mdb_start "MultiThread.exe"
mdb_expect_frame 0 "X.Main()" $file 34
mdb_send "break -group main 44"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
set new_process [mdb_expect_process]
mdb_expect_stopped 0 "X.Main()" $file 44
# mdb_send "background -process $new_process"
# mdb_expect_prompt
# mdb_expect_frame 0 "X.Main()" $file 43
# verbose "FIXME: Sleeping 3 seconds"
# sleep 3
mdb_send "step"
mdb_expect_stopped 0 "X.CommonFunction(System.Int32)" $file 15
mdb_send "step"
mdb_expect_stopped 0 "X.CommonFunction(System.Int32)" $file 21
for { set i 0 } { $i < 10 } { incr i } {
    mdb_send "next"
    mdb_expect_stopped 0 "X.CommonFunction(System.Int32)" $file 23
    # verbose "The following command will take 5 seconds to complete"
    mdb_send "next"
    mdb_expect_stopped 0 "X.CommonFunction(System.Int32)" $file 24
    mdb_send "next"
    mdb_expect_stopped 0 "X.CommonFunction(System.Int32)" $file 21
    verbose "Finished iteration $i"
}
mdb_send "kill"
mdb_send "quit"
