#!/usr/bin/expect -f
#

source $srcdir/mdb.exp

set file $srcdir/Simple.cs
mdb_start "Simple.exe"
mdb_expect_frame 0 "X.Main()" $file 7
mdb_send "start Simple.exe"
mdb_expect "ERROR: Already have a target."
mdb_send "kill"
mdb_expect_prompt
mdb_send "frame"
mdb_expect "ERROR: No program to debug."
mdb_send "start Simple.exe"
mdb_expect_started
mdb_expect_frame 0 "X.Main()" $file 7
mdb_send "restart"
mdb_expect_started
mdb_expect_frame 0 "X.Main()" $file 7
mdb_send "quit"
