#!/usr/bin/expect -f
#

source $srcdir/mdb.exp

set file $srcdir/TestAssembly.cs
set module $srcdir/TestModule.cs

mdb_start "TestAssembly.exe" "[pwd]/TestModule.dll"
mdb_expect_frame 0 "X.Main(System.String\[\])" $file 8
mdb_send "library [pwd]/TestModule.dll"
mdb_expect "Loaded library [pwd]/TestModule.dll."
mdb_expect_frame 0 "X.Main(System.String\[\])" $file 8
mdb_send "break Module.Test"
mdb_expect_breakpoint
mdb_send "continue"
mdb_expect_stopped 0 "Module.Test()" $module 4
