#!/usr/bin/expect -f
#

source $srcdir/mdb.exp

set line_world 19
set line_test 24
set line_test_2 25
set line_test_3 26
set line_porta_nigra 73
set line_roman_baths 85
set line_main 96
set line_main_2 98
set file $srcdir/TestBreakpoint.cs

set porta_nigra_url "http://de.wikipedia.org/wiki/Bild:Porta_Nigra_Trier.jpg"
set city_center_url "http://de.wikipedia.org/wiki/Bild:Trier_Innenstadt.jpg"
set roman_baths_url "http://de.wikipedia.org/wiki/Bild:Trier_roman_baths_DSC02378.jpg";

mdb_start "TestBreakpoint.exe"
mdb_expect_frame 0 "X.Main()" $file $line_main

mdb_send "break TestBreakpoint.cs:$line_test"
set bpt_1 [mdb_expect_breakpoint]
mdb_send "break $line_test_2"
set bpt_2 [mdb_expect_breakpoint]
mdb_send "break $line_test_3"
set bpt_3 [mdb_expect_breakpoint]
mdb_send "break Martin.Baulig.Hello.World"
set bpt_world [mdb_expect_breakpoint]
mdb_send "break $line_main_2"
set bpt_main_2 [mdb_expect_breakpoint]

mdb_send "continue"
mdb_expect_hit_breakpoint 0 "Martin.Baulig.Hello.Test()" $bpt_1 $file $line_test

mdb_send "break -get trier.PortaNigra"
set bpt_porta_nigra [mdb_expect_breakpoint]
# We are stopped on a breakpoint and use "continue" to step over it
mdb_send "continue"
mdb_expect_hit_breakpoint 0 "Europe.Germany.Trier.get_PortaNigra()" $bpt_porta_nigra $file $line_porta_nigra
mdb_send "next"
# Step over the breakpoint with "next"
mdb_expect_stopped 0 "Europe.Germany.Trier.get_PortaNigra()" $file [expr $line_porta_nigra + 1]

mdb_send "continue"
mdb_expect_hit_breakpoint 0 "Martin.Baulig.Hello.World(Postcard.Picture)" $bpt_world $file $line_world
mdb_send "disable $bpt_world"
mdb_expect_prompt

mdb_send "continue"
mdb_expect_line $porta_nigra_url
mdb_expect_hit_breakpoint 0 "Martin.Baulig.Hello.Test()" $bpt_2 $file $line_test_2
# We are stopped on a breakpoint and use "next" to step over it
mdb_send "next"
mdb_expect_line $city_center_url
mdb_expect_hit_breakpoint 0 "Martin.Baulig.Hello.Test()" $bpt_3 $file $line_test_3
# We are stopped on a breakpoint and use "step" to step over it
mdb_send "step"
mdb_expect_stopped 0 "Europe.Germany.Trier.get_RomanBaths()" $file $line_roman_baths

mdb_send "continue"
mdb_expect_line $roman_baths_url

mdb_expect_hit_breakpoint 0 "X.Main()" $bpt_main_2 $file $line_main_2
# We still have a breakpoint in Europe.Germany.Trier.PortaNigra's property getter while
# we're runtime-invoke'ing it.
mdb_send_and_expect "p hello.Trier.PortaNigra.URL" "(System.String) \"$porta_nigra_url\""

mdb_send "continue"
mdb_expect_line "Martin.Baulig.Hello"
mdb_expect_line "Process @4 terminated normally."
mdb_expect_prompt
mdb_send "quit"

