#!/usr/bin/expect -f
#

source $srcdir/mdb.exp

set bpt_main 30
set bpt_main_1 32

set file $srcdir/TestIndexer.cs
mdb_start "TestIndexer.exe"
mdb_expect_frame 0 "X.Main()" $file $bpt_main

mdb_send "break $bpt_main_1"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_stopped 0 "X.Main()" $file $bpt_main_1

mdb_send_and_expect "p x\[0\]" "(System.String) \"Hello\""
mdb_send_and_expect "p x\[1\]" "(System.String) \"World\""
mdb_send_and_expect "p x\[0,\"Berlin\"\]" "(System.String) \"Hello Berlin\""

mdb_send "set x\[0\] = \"Test\""
mdb_expect_prompt

mdb_send_and_expect "p x\[0\]" "(System.String) \"Test\""

mdb_send "set x\[0,\"Berlin\"] = \"Trier\""
mdb_expect_line "ERROR: Indexer `x' doesn't have a setter."
mdb_expect_prompt

mdb_send "continue"
mdb_expect_line "Test"
mdb_expect_line "Process @4 terminated normally."
mdb_expect_prompt
mdb_send "quit"
