#!/usr/bin/expect -f
#

source $srcdir/mdb.exp

set line_main 80
set line_main_2 87

set file $srcdir/TestToString.cs

mdb_start "TestToString.exe"
mdb_expect_frame 0 "X.Main()" $file $line_main
mdb_send "break $line_main_2"
set bpt_main_2 [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_hit_breakpoint 0 "X.Main()" $bpt_main_2 $file $line_main_2

mdb_send_and_expect "p /default foo" "(Foo) \{ \}"
mdb_send_and_expect "p /object foo" "(Foo) \{ \"Hello World!\" \}"
mdb_send_and_expect "p /default bar" "(Bar) \{ \}"
mdb_send_and_expect "p /object bar" "(Bar) \{ \"Hello World!\" \}"
mdb_send_and_expect "p /default hello" "(Hello) \{ PI = 3.1415 \}"
# mdb_send_and_expect "p /object hello" "(Hello) \{ \"Albert Einstein\" \}"
mdb_send_and_expect "p /default b" "(B) \{ a = 5, b = 256, c = \"Robbie Williams\" \}"
mdb_send_and_expect "p /object b" "(B) \{ a = 5, b = 256, c = \"Robbie Williams\" \}"
mdb_send_and_expect "p /default c" "(C) \{ \}"
mdb_send_and_expect "p /object c" "(C) \{ \"C (5:256:Robbie Williams)\" \}"
mdb_send_and_expect "p /default bb" "(B) \{ a = 5, b = 256, c = \"Robbie Williams\" \}"
mdb_send_and_expect "p /object bb" "(B) \{ a = 5, b = 256, c = \"Robbie Williams\" \}"

mdb_send "continue"
mdb_expect_line "Process @4 terminated normally."
mdb_expect_prompt
mdb_send "quit"

