#!/usr/bin/expect -f
#

source $srcdir/mdb.exp

set bpt_simple 120
set bpt_boxed_value 132
set bpt_boxed_ref 142
set bpt_simple_array 150
set bpt_multi_value_array 157
set bpt_string_array 164
set bpt_multi_string_array 172
set bpt_struct_type 179
set bpt_class_type 186
set bpt_inherited_class_type 195
set bpt_complex_struct_type 205
set bpt_function_struct_type 213

set file $srcdir/TestManagedTypes.cs
mdb_start "TestManagedTypes.exe"
mdb_expect_frame 0 "X.Main()" $file 218

mdb_send "break $bpt_simple"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_stopped 0 "X.Simple()" $file $bpt_simple
mdb_send_and_expect "dump -mode object a" "object:True:-1:System.Int32:True:4:Fundamental Int32"
mdb_send_and_expect "ptype a" "System.Int32"
mdb_send_and_expect "print a" "(System.Int32) 5"
mdb_send_and_expect "dump -mode object b" "object:True:-1:System.Int64:True:8:Fundamental Int64"
mdb_send_and_expect "ptype b" "System.Int64"
mdb_send_and_expect "print b" "(System.Int64) 7"
mdb_send_and_expect "dump -mode object f" "object:True:-1:System.Single:True:4:Fundamental Single"
mdb_send_and_expect "ptype f" "System.Single"
mdb_send_and_expect "print f" "(System.Single) 0.7142857"
mdb_send_and_expect "ptype hello" "System.String"
mdb_send_and_expect "print hello" "(System.String) \"Hello World\""

mdb_send "break $bpt_boxed_value"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_line "5"
mdb_expect_line "7"
mdb_expect_line "0.7142857"
mdb_expect_line "Hello World"
mdb_expect_stopped 0 "X.BoxedValueType()" $file $bpt_boxed_value
mdb_send_and_expect "print a" "(System.Int32) 5"
mdb_send_and_expect "print boxed_a" "(System.Object) &(System.Int32) 5"
mdb_send_and_expect "print *boxed_a" "(System.Int32) 5"

mdb_send "break $bpt_boxed_ref"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_line "5"
mdb_expect_line "5"
mdb_expect_stopped 0 "X.BoxedReferenceType()" $file $bpt_boxed_ref
mdb_send_and_expect "print hello" "(System.String) \"Hello World\""
mdb_send_and_expect "print boxed_hello" "(System.Object) &(System.String) \"Hello World\""
mdb_send_and_expect "print *boxed_hello" "(System.String) \"Hello World\""

mdb_send "break $bpt_simple_array"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_line "Hello World"
mdb_expect_line "Hello World"
mdb_expect_stopped 0 "X.SimpleArray()" $file $bpt_simple_array
mdb_send_and_expect "print a" "(System.Int32\[\]) \[ 3, 4, 5 \]"
mdb_send_and_expect "print a\[1\]" "(System.Int32) 4"
mdb_send "set a\[2\] = 9"
mdb_expect_prompt
mdb_send_and_expect "print a\[2\]" "(System.Int32) 9"

mdb_send "break $bpt_multi_value_array"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_line "9"
mdb_expect_stopped 0 "X.MultiValueTypeArray()" $file $bpt_multi_value_array
mdb_send_and_expect "print a" "(System.Int32\[,\]) \[ \[ 6, 7, 8 \], \[ 9, 10, 11 \] \]"
mdb_send_and_expect "print a\[1\]" "ERROR: Index of array expression `a' out of bounds."
mdb_send_and_expect "print a\[1,2\]" "(System.Int32) 11"
mdb_send_and_expect "print a\[2\]" "ERROR: Index of array expression `a' out of bounds."
# FIXME
# mdb_send "set a\[1,2\] = 50"
# mdb_expect_prompt

mdb_send "break $bpt_string_array"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_line "11"
mdb_expect_stopped 0 "X.StringArray()" $file $bpt_string_array
mdb_send_and_expect "print a" "(System.String\[\]) \[ \"Hello\", \"World\" \]"
mdb_send_and_expect "print a\[1\]" "(System.String) \"World\""
# FIXME
# mdb_send "set a\[1\] = \"Trier\""
# mdb_expect_prompt

mdb_send "break $bpt_multi_string_array"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_line "System.String\[\]"
mdb_expect_stopped 0 "X.MultiStringArray()" $file $bpt_multi_string_array
mdb_send_and_expect "print a" "(System.String\[,\]) \[ \[ \"Hello\", \"World\" \], \[ \"New York\", \"Boston\" \], \[ \"Ximian\", \"Monkeys\" \] \]"
mdb_send_and_expect "print a\[2,1\]" "(System.String) \"Monkeys\""

mdb_send "break $bpt_struct_type"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_line "System.String\[,\]"
mdb_expect_line "51.2"
mdb_expect_line "Hello World"
mdb_expect_stopped 0 "X.StructType()" $file $bpt_struct_type
mdb_send_and_expect "print a" "(A) { a = 5, b = 256, c = \"New England Patriots\", f = 51.2 }"

mdb_send "break $bpt_class_type"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_line "A"
mdb_expect_line "5"
mdb_expect_line "3.14"
mdb_expect_stopped 0 "X.ClassType()" $file $bpt_class_type
mdb_send_and_expect "print b" "(B) { a = 5, b = 256, c = \"New England Patriots\" }"

mdb_send "break $bpt_inherited_class_type"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_line "B"
mdb_expect_line "8"
mdb_expect_stopped 0 "X.InheritedClassType()" $file $bpt_inherited_class_type
mdb_send_and_expect "print c" "(C) { a = 8, f = 3.14 }"
mdb_send_and_expect "print b" "(B) { a = 5, b = 256, c = \"New England Patriots\" }"
mdb_send_and_expect "print (B) c" "(B) { a = 5, b = 256, c = \"New England Patriots\" }"

mdb_send "break $bpt_complex_struct_type"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_line "5"
mdb_expect_stopped 0 "X.ComplexStructType()" $file $bpt_complex_struct_type
mdb_send_and_expect "print d.a" "(A) { a = 5, b = 256, c = \"New England Patriots\", f = 51.2 }"
mdb_send_and_expect "print d.b" "(B) { a = 5, b = 256, c = \"New England Patriots\" }"
mdb_send_and_expect "print d.c" "(C) { a = 8, f = 3.14 }"
mdb_send_and_expect "print d.s" "(System.String\[\]) \[ \"Eintracht Trier\" \]"

mdb_send "break $bpt_function_struct_type"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_line "Eintracht Trier"
mdb_expect_stopped 0 "X.FunctionStructType()" $file $bpt_function_struct_type
mdb_send_and_expect "print e" "(E) { a = 9 }"
mdb_send_and_expect "print e.a" "(System.Int32) 9"
mdb_send_and_expect "print e.Foo (5)" "(System.Int64) 5"

mdb_send "continue"

mdb_expect_line "9"
mdb_expect_line "Process @4 terminated normally."
mdb_expect_prompt
mdb_send "quit"
