#!/usr/bin/expect -f
#

source $srcdir/mdb.exp

set file $srcdir/TestInheritance.cs
mdb_start "TestInheritance.exe"
mdb_expect_frame 0 "X.Main()" $file 119
mdb_send "break 123"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_stopped 0 "X.Main()" $file 123
mdb_send "print d.Test ()"
mdb_expect "\"Hello World\""
mdb_send "print a.Test ()"
mdb_expect "\"Hello World\""
mdb_send "print a.ToString ()"
mdb_expect "\"5\""
mdb_send "print (A) a"
mdb_expect "{5, \"Hello World\"}"
mdb_send "print (B) a"
mdb_expect "ERROR: Cannot cast from A to B."
mdb_send "print d"
mdb_expect "{500}"
mdb_send "print (C) d"
mdb_expect "{3.14}"
mdb_send "print (B) d"
mdb_expect "{8, \"Hello World\"}"
mdb_send "print (A) d"
mdb_expect "ERROR: Cannot cast from D to A."
mdb_send "print (D) d"
mdb_expect "{500}"
mdb_send "print ((D) d)"
mdb_expect "{500}"
mdb_send "print (((D) d))"
mdb_expect "{500}"
mdb_send "print ((B) d).Test ()"
mdb_expect "\"Hello World\""
mdb_send "print ((C) d).Test ()"
mdb_expect "\"Hello World\""
mdb_send "print (((D) d).Test ())"
mdb_expect "\"Hello World\""
mdb_send "print d.Hello ()"
mdb_expect "ERROR: Method `d.Hello ()' doesn't return a value."
mdb_send "print d.Virtual ()"
mdb_expect "2"
mdb_send "print ((C) d).Virtual ()"
mdb_expect "1"
mdb_send "quit"
