#!/usr/bin/expect -f
#

source $srcdir/mdb.exp

set file $srcdir/TestDelegate.cs
mdb_start "TestDelegate.exe"
mdb_expect_frame 0 "X.Main()" $file 29
mdb_send "next"
mdb_expect_stopped 0 "X.Main()" $file 30
mdb_send "p x.Foo (8)"
mdb_expect_line "Hello World: 8"
mdb_expect_line "Boston: 8"
mdb_expect_line "(System.Int64) 24"
mdb_expect_prompt
mdb_send "p x.Foo (9)"
mdb_expect_line "Hello World: 9"
mdb_expect_line "Boston: 9"
mdb_expect_line "(System.Int64) 27"
mdb_expect_prompt
mdb_send "step"
mdb_expect_stopped 0 "X.foo(System.Int32)" $file 17
mdb_send "next"
mdb_expect_line "Hello World: 4"
mdb_expect_stopped 0 "X.foo(System.Int32)" $file 18
mdb_send "step"
mdb_expect_stopped 0 "X.foo(System.Int32)" $file 19
mdb_send "step"
mdb_expect_stopped 0 "X.boston(System.Int32)" $file 23
mdb_send "next"
mdb_expect_line "Boston: 4"
mdb_expect_stopped 0 "X.boston(System.Int32)" $file 24
mdb_send "step"
mdb_expect_stopped 0 "X.boston(System.Int32)" $file 25
mdb_send "step"
mdb_expect_stopped 0 "X.Main()" $file 31
mdb_send "p x.Foo (5)"
mdb_expect_line "Hello World: 5"
mdb_expect_line "Boston: 5"
mdb_expect_line "(System.Int64) 15"
mdb_expect_prompt
mdb_send "p x.Foo (3)"
mdb_expect_line "Hello World: 3"
mdb_expect_line "Boston: 3"
mdb_expect_line "(System.Int64) 9"
mdb_expect_prompt
mdb_send "b -invoke x.Foo"
set bpt [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_line "Back in main"
mdb_expect_stopped 0 "X.foo(System.Int32)" $file 17
mdb_send "next"
mdb_expect_line "Hello World: 11"
mdb_expect_stopped 0 "X.foo(System.Int32)" $file 18
mdb_send "step"
mdb_expect_stopped 0 "X.foo(System.Int32)" $file 19
mdb_send "step"
mdb_expect_stopped 0 "X.boston(System.Int32)" $file 23
mdb_send "next"
mdb_expect_line "Boston: 11"
mdb_expect_stopped 0 "X.boston(System.Int32)" $file 24
mdb_send "step"
mdb_expect_stopped 0 "X.boston(System.Int32)" $file 25
mdb_send "step"
mdb_expect_stopped 0 "X.Main()" $file 33
mdb_send "continue"
mdb_expect_line "Thread @1 terminated normally."
mdb_expect_prompt
mdb_send "quit"
