#!/usr/bin/expect -f
#

source $srcdir/mdb.exp

set line_world 12
set line_test 18
set line_porta_nigra 58
set line_main 76
set file $srcdir/TestBreakpoint.cs

mdb_start "TestBreakpoint.exe"
mdb_expect_frame 0 "X.Main()" $file $line_main

mdb_send "break TestBreakpoint.cs:$line_test"
set bpt_1 [mdb_expect_breakpoint]
mdb_send "break Martin.Baulig.Hello.World"
set bpt_2 [mdb_expect_breakpoint]

mdb_send "continue"
mdb_expect_stopped 0 "Martin.Baulig.Hello.Test()" $file $line_test

# mdb_send "break -get Trier.PortaNigra"
# set bpt_3 [mdb_expect_breakpoint]
# mdb_send "continue"
# mdb_expect_stopped 0 "Europe.Germany.Trier.get_PortaNigra()" $file $line_porta_nigra

mdb_send "continue"
mdb_expect_stopped 0 "Martin.Baulig.Hello.World(Postcard.Picture)" $file $line_world

mdb_send "continue"

mdb_expect_line "http://de.wikipedia.org/wiki/Bild:Porta_Nigra_Trier.jpg"
mdb_expect_line "Process @4 terminated normally."
mdb_expect_prompt
mdb_send "quit"

