#!/usr/bin/expect -f
#

source $srcdir/mdb.exp

set file $srcdir/TestDelegate.cs
mdb_start "TestDelegate.exe"
mdb_expect_frame 0 "X.Main()" $file 27
mdb_send "next"
mdb_expect_stopped 0 "X.Main()" $file 28
mdb_send "step"
mdb_expect_stopped 0 "X.foo()" $file 17
mdb_send "next"
mdb_expect_line "Hello World"
mdb_expect_stopped 0 "X.foo()" $file 18
mdb_send "step"
mdb_expect_stopped 0 "X.boston()" $file 22
mdb_send "next"
mdb_expect_line "Boston"
mdb_expect_stopped 0 "X.boston()" $file 23
mdb_send "step"
mdb_expect_stopped 0 "X.Main()" $file 29
mdb_send "continue"
mdb_expect_prompt
mdb_send "quit"
