#!/usr/bin/expect -f
#

source $srcdir/mdb.exp

set file $srcdir/TestRestart.cs
mdb_start "TestRestart.exe"
mdb_expect_frame 0 "X.Main()" $file 7

mdb_send "continue"
mdb_expect_line "Hello World"
mdb_expect_line "Process @1 terminated normally."
mdb_expect_prompt

mdb_send "run"
mdb_expect_started
mdb_expect_frame 0 "X.Main()" $file 7
mdb_send "continue"
mdb_expect_line "Hello World"
mdb_expect_line "Process @1 terminated normally."
mdb_expect_prompt

mdb_send "run"
mdb_expect_started
mdb_expect_frame 0 "X.Main()" $file 7
mdb_send "continue"
mdb_expect_line "Hello World"
mdb_expect_line "Process @1 terminated normally."
mdb_expect_prompt

mdb_send "run"
mdb_expect_started
mdb_expect_frame 0 "X.Main()" $file 7
mdb_send "continue"
mdb_expect_line "Hello World"
mdb_expect_line "Process @1 terminated normally."
mdb_expect_prompt

mdb_send "run"
mdb_expect_started
mdb_expect_frame 0 "X.Main()" $file 7
mdb_send "continue"
mdb_expect_line "Hello World"
mdb_expect_line "Process @1 terminated normally."
mdb_expect_prompt

mdb_send "run"
mdb_expect_started
mdb_expect_frame 0 "X.Main()" $file 7
mdb_send "continue"
mdb_expect_line "Hello World"
mdb_expect_line "Process @1 terminated normally."
mdb_expect_prompt

mdb_send "quit"

