#!/usr/bin/expect -f
#

source $srcdir/mdb.exp

set file $srcdir/TestException.cs
mdb_start "TestException.exe"
mdb_expect_frame 0 "X.Main()" $file 12
mdb_send "catch InvalidOperationException"
set catchpoint [mdb_expect_catchpoint]
mdb_send "break 19"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_exception 0 "X.Test()" $file 7
mdb_send "continue"
mdb_expect_line "EXCEPTION: System.InvalidOperationException"
mdb_expect_stopped 0 "X.Main()" $file 19
mdb_send "continue"
mdb_expect_line "Done"
mdb_expect_line "Process @4 terminated normally."
mdb_expect_prompt
mdb_send "quit"
