#!/usr/bin/expect -f
#

source $srcdir/mdb.exp

set bpt_main 43
set bpt_1 44
set file $srcdir/TestProperty.cs

mdb_start "TestProperty.exe"
mdb_expect_frame 0 "X.Main()" $file $bpt_main
mdb_send "break $bpt_1"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_stopped  0 "X.Main()" $file $bpt_1

mdb_send_and_expect "p test.A" "(A) { }"
mdb_send_and_expect "p test.B" "(B\[\]) \[ { } \]"
mdb_send_and_expect "p test.C" "(C\[,\]) \[  \]"
mdb_send_and_expect "p test.Hello (new D ())" "(System.String) \"D\""

mdb_send "continue"
mdb_expect_line "Test"
mdb_expect_line "Process @4 terminated normally."
mdb_expect_prompt
mdb_send "quit"

