#!/usr/bin/expect -f
#

source $srcdir/mdb.exp

set line_main 140
set line_main_2 152
set bpt_hello 90

set file $srcdir/TestInheritance.cs
mdb_start "TestInheritance.exe"
mdb_expect_frame 0 "X.Main()" $file $line_main
mdb_send "break $line_main_2"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_hit_breakpoint 0 "X.Main()" $breakpoint $file $line_main_2
mdb_send_and_expect "print d.Test ()" "(System.String) \"Hello World\""
mdb_send_and_expect "print a.Test ()" "(System.String) \"Hello World\""
mdb_send_and_expect "print a.ToString ()" "(System.String) \"5\""
mdb_send_and_expect "print (A) a" "(A) { a = 5, Hello = \"Hello World\" }"
mdb_send_and_expect "print (B) a" "ERROR: Cannot cast from A to B."
mdb_send_and_expect "print d" "(D) { e = 500 }"
mdb_send_and_expect "print (C) d" "(C) { f = 3.14 }"
mdb_send_and_expect "print (B) d" "(B) { a = 8, Hello = \"Hello World\" }"
mdb_send_and_expect "print (A) d" "ERROR: Cannot cast from D to A."
mdb_send_and_expect "print (D) d" "(D) { e = 500 }"
mdb_send_and_expect "print ((D) d)" "(D) { e = 500 }"
mdb_send_and_expect "print (((D) d))" "(D) { e = 500 }"
mdb_send_and_expect "print ((B) d).Test ()" "(System.String) \"Hello World\""
mdb_send_and_expect "print ((C) d).Test ()" "(System.String) \"Hello World\""
mdb_send_and_expect "print (((D) d).Test ())" "(System.String) \"Hello World\""
mdb_send_and_expect "print d.Hello ()" "ERROR: Method `d.Hello ()' doesn't return a value."
mdb_send_and_expect "print d.Virtual ()" "(System.Int32) 2"
mdb_send_and_expect "print ((C) d).Virtual ()" "(System.Int32) 2"
mdb_send_and_expect "print a.Hello" "(System.String) \"Hello World\""
mdb_send_and_expect "print a.Property" "(System.String) \"Hello World\""
mdb_send_and_expect "print A.StaticTest ()" "(System.String) \"Boston\""
mdb_send_and_expect "print A.StaticProperty" "(System.String) \"Boston\""
mdb_send_and_expect "print ((B) d).Hello" "(System.String) \"Hello World\""
mdb_send_and_expect "print ((B) d).Property" "(System.String) \"Hello World\""
mdb_send_and_expect "print B.StaticTest ()" "(System.String) \"Boston\""
mdb_send_and_expect "print B.StaticProperty" "(System.String) \"Boston\""
mdb_send_and_expect "print d.f" "(System.Single) 3.14"
mdb_send_and_expect "print d.a" "(System.Int32) 8"
mdb_send_and_expect "print c.Virtual ()" "(System.Int32) 2"
mdb_send_and_expect "print hello.Test ()" "(System.String) \"Hello\""
mdb_send_and_expect "print world.Test ()" "(System.String) \"World\""
mdb_send "break $bpt_hello"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_line "Hello"
mdb_expect_line "World"
mdb_expect_line "3.14"
mdb_expect_hit_breakpoint 0 "C.Hello()" $breakpoint $file $bpt_hello
mdb_send_and_expect "print this" "(C) { f = 3.14 }"
mdb_send_and_expect "print f" "(System.Single) 3.14"
mdb_send_and_expect "print base.a" "(System.Int32) 8"
mdb_send_and_expect "print base.Hello" "(System.String) \"Hello World\""
mdb_send_and_expect "print Virtual ()" "(System.Int32) 2"
mdb_send "continue"
mdb_expect_line "Process @4 terminated normally."
mdb_expect_prompt
mdb_send "quit"
