#!/usr/bin/expect -f
#

source $srcdir/mdb.exp

set file $srcdir/TestNamespace.cs
mdb_start "TestNamespace.exe"
mdb_expect_frame 0 "Test.X.Main()" $file 36
mdb_send "break 12"
set breakpoint [mdb_expect_breakpoint]
mdb_send "continue"
mdb_expect_hit_breakpoint  0 "Martin.Baulig.Hello.World()" $breakpoint $file 12
mdb_send "print Foo.Print ()"
mdb_expect "(System.String) \"Boston\""
mdb_send "print Foo.Boston"
mdb_expect "(System.String) \"Boston\""
mdb_send "continue"
mdb_expect_line "Boston"
mdb_expect_line "Process @4 terminated normally."
mdb_expect_prompt
mdb_send "quit"
